In [1]:
# gmean without funtion

a=20
b=30
gmean=(a*b)/(a+b)
print(gmean)

c=10
d=20
gmean1=(c*d)/(c+d)
print(gmean1)

12.0
6.666666666666667

In [2]:
# gmean funtion
def gmean(a,b):
  mean=(a*b)/(a+b)
  print(mean)
gmean(20,30)
gmean(10,20)

12.0
6.666666666666667

In [3]:
def even_or_odd(num):
  if num%2==0:
    return "Even"
  else:
    return "Odd"
print(even_or_odd(4))
print(even_or_odd(9))

Even
Odd

In [4]:
#funtion without parameter

def greet():
  print("Hello World")
greet()

Hello World

In [5]:
#funtion with parameter

def student(name):
  print("Hello",name)
student("Prashant")

Hello Prashant

In [6]:
#simple interest funtion

def simple_interest(p,t,r):
  SI=(p*t*r)/100
  print(f"Simple interest: {SI}")
simple_interest(500,6,5)

Simple interest: 150.0

In [7]:
# Area of Rectangle

def rectArea(l,w):
  area=l*w
  print(f"Area of Rectangle: {area}")
rectArea(5,8)

Area of Rectangle: 40

In [8]:
# Area of triangle

def triangle_Area(b,h):
  area=0.5*b*h
  print(f"Area of triangle: {area}")
triangle_Area(5,8)

Area of triangle: 20.0

In [9]:
# Area of square and circle

def square_area(s):
  square=s*s
  print(f"Area of square: {square}")
square_area(5)

def circle_area(r):
  circle=3.14159*(r**2)
  print(f"Area of circle: {circle}")
circle_area(4)

Area of square: 25
Area of circle: 50.26544

In [10]:
# Exception Handling

a = input("Enter a number:")
print(f"Multiplication table of {a} is:")
try:
  for i in range(1,11):
    print(f"{int(a)} * {i} = {int(a)*i}")
except:
  print("Invalid input")

Enter a number:5
Multiplication table of 5 is:
5 * 1 = 5
5 * 2 = 10
5 * 3 = 15
5 * 4 = 20
5 * 5 = 25
5 * 6 = 30
5 * 7 = 35
5 * 8 = 40
5 * 9 = 45
5 * 10 = 50

In [11]:
# Login page

correct_phone=123
correct_pass="pass"

try:
 print("User login page")
 phone=int(input("Enter your Phone number:"))
 password=input("Enter Password:")
 if phone == correct_phone and password==correct_pass:
  print("Login successfully")
 else:
  print("Invalid username of password")

except:
  print("Enter valid inputs")

User login page
Enter your Phone number:123
Enter Password:pass
Login successfully

In [12]:
try:
  res=10/0
  print(res)
except:
  print("Can not divided by zero")

Can not divided by zero

In [13]:
from google.colab import files
uploaded=files.upload()

Saving data_cleaning_dataset_1.csv to data_cleaning_dataset_1.csv

In [14]:
import pandas as pd
df=pd.read_csv("data_cleaning_dataset_1.csv")
#df.head() #Reading 1st 5 rows
print(df)

     Student_ID    Age  Gender  Marks  Attendance_Percent Department  \
0             1  150.0     NaN  -10.0                 NaN        NaN
1             2   21.0  Female   65.0                60.0        BBA
2             3   22.0       M   65.0               100.0        NaN
3             4  150.0    Male  -10.0                70.0        NaN
4             5   20.0    male  -10.0               100.0        BBA
..          ...    ...     ...    ...                 ...        ...
995         996    NaN       F   75.0                 NaN       BCOM
996         997   18.0    male  -10.0                 NaN        BCA
997         998  150.0    male    NaN                70.0        BSc
998         999   21.0    Male   85.0               100.0        BCA
999        1000    NaN  Female  -10.0                90.0        BSc

          City            Email Fee_Paid Admission_Date  Income  Study_Hours  \
0       Mumbai              NaN       No     15-07-2023  136958          9.2
1    Bangalore              NaN        Y     15-07-2023  146932          2.1
2          NaN              NaN        N            NaN  118694          6.2
3       Mumbai              NaN        N     01-06-2023  134879          3.5
4      Chennai  valid@email.com      NaN     15-07-2023  125268          6.0
..         ...              ...      ...            ...     ...          ...
995     Mumbai  valid@email.com        N     15-07-2023   70961          6.0
996    Chennai              NaN        N            NaN  141678          6.4
997    Chennai              NaN        N            NaN   89532          7.1
998        NaN              NaN        N     01-06-2023   96994          8.2
999      Delhi  valid@email.com      NaN     15-08-2023   71133          3.4

     Experience_Years Course_Level Scholarship Hostel Blood_Group
0                   2           UG          No     No          B+
1                   0           PG          No     No          A+
2                   2           PG         Yes    Yes          B-
3                   5           UG         Yes     No          O-
4                   7          PhD          No     No          O+
..                ...          ...         ...    ...         ...
995                 5           UG         Yes    Yes          A-
996                 3           UG         Yes     No          O+
997                 7           UG         Yes    Yes         AB+
998                 2           UG         Yes     No          B-
999                 8          PhD         Yes    Yes          O-

[1000 rows x 17 columns]

In [15]:
#To know about Rows and Columns
df.shape

(1000, 17)

In [16]:
#To know the duplicated values
df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
995    False
996    False
997    False
998    False
999    False
Length: 1000, dtype: bool

In [17]:
#To remove the duplicated values
df.drop_duplicates(inplace=True)

In [18]:
#To know the null values
df.isnull()

,Student_ID,Age,Gender,Marks,Attendance_Percent,Department,City,Email,Fee_Paid,Admission_Date,Income,Study_Hours,Experience_Years,Course_Level,Scholarship,Hostel,Blood_Group
0,False,False,True,False,True,True,False,True,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,True,True,True,False,True,False,False,False,False,False,False,False
3,False,False,False,False,False,True,False,True,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,False,True,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False
996,False,False,False,False,True,False,False,True,False,True,False,False,False,False,False,False,False
997,False,False,False,True,False,False,False,True,False,True,False,False,False,False,False,False,False
998,False,False,False,False,False,False,True,True,False,False,False,False,False,False,False,False,False
999,False,True,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False

In [19]:
#To know total no of null values within each columns
df.isnull().sum()

Student_ID              0
Age                   135
Gender                143
Marks                 106
Attendance_Percent    162
Department            203
City                  199
Email                 340
Fee_Paid              212
Admission_Date        234
Income                  0
Study_Hours             0
Experience_Years        0
Course_Level            0
Scholarship             0
Hostel                  0
Blood_Group             0
dtype: int64

In [20]:
# Handling missing values

# Numerical Columns --> fill with midian

num_cols=["Age","Marks","Attendance_Percent"]

#with for loop
for col in num_cols:
  df[col]=df[col].fillna(df[col].median())
print(df)

     Student_ID    Age  Gender  Marks  Attendance_Percent Department  \
0             1  150.0     NaN  -10.0                80.0        NaN
1             2   21.0  Female   65.0                60.0        BBA
2             3   22.0       M   65.0               100.0        NaN
3             4  150.0    Male  -10.0                70.0        NaN
4             5   20.0    male  -10.0               100.0        BBA
..          ...    ...     ...    ...                 ...        ...
995         996   21.0       F   75.0                80.0       BCOM
996         997   18.0    male  -10.0                80.0        BCA
997         998  150.0    male   75.0                70.0        BSc
998         999   21.0    Male   85.0               100.0        BCA
999        1000   21.0  Female  -10.0                90.0        BSc

          City            Email Fee_Paid Admission_Date  Income  Study_Hours  \
0       Mumbai              NaN       No     15-07-2023  136958          9.2
1    Bangalore              NaN        Y     15-07-2023  146932          2.1
2          NaN              NaN        N            NaN  118694          6.2
3       Mumbai              NaN        N     01-06-2023  134879          3.5
4      Chennai  valid@email.com      NaN     15-07-2023  125268          6.0
..         ...              ...      ...            ...     ...          ...
995     Mumbai  valid@email.com        N     15-07-2023   70961          6.0
996    Chennai              NaN        N            NaN  141678          6.4
997    Chennai              NaN        N            NaN   89532          7.1
998        NaN              NaN        N     01-06-2023   96994          8.2
999      Delhi  valid@email.com      NaN     15-08-2023   71133          3.4

     Experience_Years Course_Level Scholarship Hostel Blood_Group
0                   2           UG          No     No          B+
1                   0           PG          No     No          A+
2                   2           PG         Yes    Yes          B-
3                   5           UG         Yes     No          O-
4                   7          PhD          No     No          O+
..                ...          ...         ...    ...         ...
995                 5           UG         Yes    Yes          A-
996                 3           UG         Yes     No          O+
997                 7           UG         Yes    Yes         AB+
998                 2           UG         Yes     No          B-
999                 8          PhD         Yes    Yes          O-

[1000 rows x 17 columns]

In [21]:
# Handling missing values

# Numerical Columns --> fill with midian

num_cols=["Age","Marks","Attendance_Percent"]

#without for loop
df[num_cols]=df[num_cols].fillna(df[num_cols].median())
print(df)

     Student_ID    Age  Gender  Marks  Attendance_Percent Department  \
0             1  150.0     NaN  -10.0                80.0        NaN
1             2   21.0  Female   65.0                60.0        BBA
2             3   22.0       M   65.0               100.0        NaN
3             4  150.0    Male  -10.0                70.0        NaN
4             5   20.0    male  -10.0               100.0        BBA
..          ...    ...     ...    ...                 ...        ...
995         996   21.0       F   75.0                80.0       BCOM
996         997   18.0    male  -10.0                80.0        BCA
997         998  150.0    male   75.0                70.0        BSc
998         999   21.0    Male   85.0               100.0        BCA
999        1000   21.0  Female  -10.0                90.0        BSc

          City            Email Fee_Paid Admission_Date  Income  Study_Hours  \
0       Mumbai              NaN       No     15-07-2023  136958          9.2
1    Bangalore              NaN        Y     15-07-2023  146932          2.1
2          NaN              NaN        N            NaN  118694          6.2
3       Mumbai              NaN        N     01-06-2023  134879          3.5
4      Chennai  valid@email.com      NaN     15-07-2023  125268          6.0
..         ...              ...      ...            ...     ...          ...
995     Mumbai  valid@email.com        N     15-07-2023   70961          6.0
996    Chennai              NaN        N            NaN  141678          6.4
997    Chennai              NaN        N            NaN   89532          7.1
998        NaN              NaN        N     01-06-2023   96994          8.2
999      Delhi  valid@email.com      NaN     15-08-2023   71133          3.4

     Experience_Years Course_Level Scholarship Hostel Blood_Group
0                   2           UG          No     No          B+
1                   0           PG          No     No          A+
2                   2           PG         Yes    Yes          B-
3                   5           UG         Yes     No          O-
4                   7          PhD          No     No          O+
..                ...          ...         ...    ...         ...
995                 5           UG         Yes    Yes          A-
996                 3           UG         Yes     No          O+
997                 7           UG         Yes    Yes         AB+
998                 2           UG         Yes     No          B-
999                 8          PhD         Yes    Yes          O-

[1000 rows x 17 columns]

In [22]:
#Categorical colums
cat_cols=["Gender","Department","City","Fee_Paid"]

# With for loop
for col in cat_cols:
  df[col]=df[col].fillna(df[col].mode()[0])
print(df)

     Student_ID    Age  Gender  Marks  Attendance_Percent Department  \
0             1  150.0    Male  -10.0                80.0       BCOM
1             2   21.0  Female   65.0                60.0        BBA
2             3   22.0       M   65.0               100.0       BCOM
3             4  150.0    Male  -10.0                70.0       BCOM
4             5   20.0    male  -10.0               100.0        BBA
..          ...    ...     ...    ...                 ...        ...
995         996   21.0       F   75.0                80.0       BCOM
996         997   18.0    male  -10.0                80.0        BCA
997         998  150.0    male   75.0                70.0        BSc
998         999   21.0    Male   85.0               100.0        BCA
999        1000   21.0  Female  -10.0                90.0        BSc

          City            Email Fee_Paid Admission_Date  Income  Study_Hours  \
0       Mumbai              NaN       No     15-07-2023  136958          9.2
1    Bangalore              NaN        Y     15-07-2023  146932          2.1
2      Chennai              NaN        N            NaN  118694          6.2
3       Mumbai              NaN        N     01-06-2023  134879          3.5
4      Chennai  valid@email.com       No     15-07-2023  125268          6.0
..         ...              ...      ...            ...     ...          ...
995     Mumbai  valid@email.com        N     15-07-2023   70961          6.0
996    Chennai              NaN        N            NaN  141678          6.4
997    Chennai              NaN        N            NaN   89532          7.1
998    Chennai              NaN        N     01-06-2023   96994          8.2
999      Delhi  valid@email.com       No     15-08-2023   71133          3.4

     Experience_Years Course_Level Scholarship Hostel Blood_Group
0                   2           UG          No     No          B+
1                   0           PG          No     No          A+
2                   2           PG         Yes    Yes          B-
3                   5           UG         Yes     No          O-
4                   7          PhD          No     No          O+
..                ...          ...         ...    ...         ...
995                 5           UG         Yes    Yes          A-
996                 3           UG         Yes     No          O+
997                 7           UG         Yes    Yes         AB+
998                 2           UG         Yes     No          B-
999                 8          PhD         Yes    Yes          O-

[1000 rows x 17 columns]

In [23]:
df.isnull().sum()

Student_ID              0
Age                     0
Gender                  0
Marks                   0
Attendance_Percent      0
Department              0
City                    0
Email                 340
Fee_Paid                0
Admission_Date        234
Income                  0
Study_Hours             0
Experience_Years        0
Course_Level            0
Scholarship             0
Hostel                  0
Blood_Group             0
dtype: int64

In [24]:
#Categorical colums
cat_cols=["Gender","Department","City","Fee_Paid"]

# Without for loop
df[col]=df[col].fillna(df[col].mode()[0])
print(df)

     Student_ID    Age  Gender  Marks  Attendance_Percent Department  \
0             1  150.0    Male  -10.0                80.0       BCOM
1             2   21.0  Female   65.0                60.0        BBA
2             3   22.0       M   65.0               100.0       BCOM
3             4  150.0    Male  -10.0                70.0       BCOM
4             5   20.0    male  -10.0               100.0        BBA
..          ...    ...     ...    ...                 ...        ...
995         996   21.0       F   75.0                80.0       BCOM
996         997   18.0    male  -10.0                80.0        BCA
997         998  150.0    male   75.0                70.0        BSc
998         999   21.0    Male   85.0               100.0        BCA
999        1000   21.0  Female  -10.0                90.0        BSc

          City            Email Fee_Paid Admission_Date  Income  Study_Hours  \
0       Mumbai              NaN       No     15-07-2023  136958          9.2
1    Bangalore              NaN        Y     15-07-2023  146932          2.1
2      Chennai              NaN        N            NaN  118694          6.2
3       Mumbai              NaN        N     01-06-2023  134879          3.5
4      Chennai  valid@email.com       No     15-07-2023  125268          6.0
..         ...              ...      ...            ...     ...          ...
995     Mumbai  valid@email.com        N     15-07-2023   70961          6.0
996    Chennai              NaN        N            NaN  141678          6.4
997    Chennai              NaN        N            NaN   89532          7.1
998    Chennai              NaN        N     01-06-2023   96994          8.2
999      Delhi  valid@email.com       No     15-08-2023   71133          3.4

     Experience_Years Course_Level Scholarship Hostel Blood_Group
0                   2           UG          No     No          B+
1                   0           PG          No     No          A+
2                   2           PG         Yes    Yes          B-
3                   5           UG         Yes     No          O-
4                   7          PhD          No     No          O+
..                ...          ...         ...    ...         ...
995                 5           UG         Yes    Yes          A-
996                 3           UG         Yes     No          O+
997                 7           UG         Yes    Yes         AB+
998                 2           UG         Yes     No          B-
999                 8          PhD         Yes    Yes          O-

[1000 rows x 17 columns]

In [25]:
#Email --> fill missing with "unknown"

email_cols=["Email"]
df[email_cols]=df[email_cols].fillna("unknown")
print(df)

# df["Email"]=df["Email"].fillna("unknown")
# print(df)

     Student_ID    Age  Gender  Marks  Attendance_Percent Department  \
0             1  150.0    Male  -10.0                80.0       BCOM
1             2   21.0  Female   65.0                60.0        BBA
2             3   22.0       M   65.0               100.0       BCOM
3             4  150.0    Male  -10.0                70.0       BCOM
4             5   20.0    male  -10.0               100.0        BBA
..          ...    ...     ...    ...                 ...        ...
995         996   21.0       F   75.0                80.0       BCOM
996         997   18.0    male  -10.0                80.0        BCA
997         998  150.0    male   75.0                70.0        BSc
998         999   21.0    Male   85.0               100.0        BCA
999        1000   21.0  Female  -10.0                90.0        BSc

          City            Email Fee_Paid Admission_Date  Income  Study_Hours  \
0       Mumbai          unknown       No     15-07-2023  136958          9.2
1    Bangalore          unknown        Y     15-07-2023  146932          2.1
2      Chennai          unknown        N            NaN  118694          6.2
3       Mumbai          unknown        N     01-06-2023  134879          3.5
4      Chennai  valid@email.com       No     15-07-2023  125268          6.0
..         ...              ...      ...            ...     ...          ...
995     Mumbai  valid@email.com        N     15-07-2023   70961          6.0
996    Chennai          unknown        N            NaN  141678          6.4
997    Chennai          unknown        N            NaN   89532          7.1
998    Chennai          unknown        N     01-06-2023   96994          8.2
999      Delhi  valid@email.com       No     15-08-2023   71133          3.4

     Experience_Years Course_Level Scholarship Hostel Blood_Group
0                   2           UG          No     No          B+
1                   0           PG          No     No          A+
2                   2           PG         Yes    Yes          B-
3                   5           UG         Yes     No          O-
4                   7          PhD          No     No          O+
..                ...          ...         ...    ...         ...
995                 5           UG         Yes    Yes          A-
996                 3           UG         Yes     No          O+
997                 7           UG         Yes    Yes         AB+
998                 2           UG         Yes     No          B-
999                 8          PhD         Yes    Yes          O-

[1000 rows x 17 columns]

In [26]:
# Gender Standardization

df["Gender"]=df["Gender"].replace({
    "M":"Male",
    "F":"Female",
    "male":"Male",
    "female":"Female"
})
print(df)

     Student_ID    Age  Gender  Marks  Attendance_Percent Department  \
0             1  150.0    Male  -10.0                80.0       BCOM
1             2   21.0  Female   65.0                60.0        BBA
2             3   22.0    Male   65.0               100.0       BCOM
3             4  150.0    Male  -10.0                70.0       BCOM
4             5   20.0    Male  -10.0               100.0        BBA
..          ...    ...     ...    ...                 ...        ...
995         996   21.0  Female   75.0                80.0       BCOM
996         997   18.0    Male  -10.0                80.0        BCA
997         998  150.0    Male   75.0                70.0        BSc
998         999   21.0    Male   85.0               100.0        BCA
999        1000   21.0  Female  -10.0                90.0        BSc

          City            Email Fee_Paid Admission_Date  Income  Study_Hours  \
0       Mumbai          unknown       No     15-07-2023  136958          9.2
1    Bangalore          unknown        Y     15-07-2023  146932          2.1
2      Chennai          unknown        N            NaN  118694          6.2
3       Mumbai          unknown        N     01-06-2023  134879          3.5
4      Chennai  valid@email.com       No     15-07-2023  125268          6.0
..         ...              ...      ...            ...     ...          ...
995     Mumbai  valid@email.com        N     15-07-2023   70961          6.0
996    Chennai          unknown        N            NaN  141678          6.4
997    Chennai          unknown        N            NaN   89532          7.1
998    Chennai          unknown        N     01-06-2023   96994          8.2
999      Delhi  valid@email.com       No     15-08-2023   71133          3.4

     Experience_Years Course_Level Scholarship Hostel Blood_Group
0                   2           UG          No     No          B+
1                   0           PG          No     No          A+
2                   2           PG         Yes    Yes          B-
3                   5           UG         Yes     No          O-
4                   7          PhD          No     No          O+
..                ...          ...         ...    ...         ...
995                 5           UG         Yes    Yes          A-
996                 3           UG         Yes     No          O+
997                 7           UG         Yes    Yes         AB+
998                 2           UG         Yes     No          B-
999                 8          PhD         Yes    Yes          O-

[1000 rows x 17 columns]

In [27]:
# Fee-Paid Standardization

df["Fee_Paid"]=df["Fee_Paid"].replace({
    "Y":"Yes",
    "N":"No"
})
print(df)

     Student_ID    Age  Gender  Marks  Attendance_Percent Department  \
0             1  150.0    Male  -10.0                80.0       BCOM
1             2   21.0  Female   65.0                60.0        BBA
2             3   22.0    Male   65.0               100.0       BCOM
3             4  150.0    Male  -10.0                70.0       BCOM
4             5   20.0    Male  -10.0               100.0        BBA
..          ...    ...     ...    ...                 ...        ...
995         996   21.0  Female   75.0                80.0       BCOM
996         997   18.0    Male  -10.0                80.0        BCA
997         998  150.0    Male   75.0                70.0        BSc
998         999   21.0    Male   85.0               100.0        BCA
999        1000   21.0  Female  -10.0                90.0        BSc

          City            Email Fee_Paid Admission_Date  Income  Study_Hours  \
0       Mumbai          unknown       No     15-07-2023  136958          9.2
1    Bangalore          unknown      Yes     15-07-2023  146932          2.1
2      Chennai          unknown       No            NaN  118694          6.2
3       Mumbai          unknown       No     01-06-2023  134879          3.5
4      Chennai  valid@email.com       No     15-07-2023  125268          6.0
..         ...              ...      ...            ...     ...          ...
995     Mumbai  valid@email.com       No     15-07-2023   70961          6.0
996    Chennai          unknown       No            NaN  141678          6.4
997    Chennai          unknown       No            NaN   89532          7.1
998    Chennai          unknown       No     01-06-2023   96994          8.2
999      Delhi  valid@email.com       No     15-08-2023   71133          3.4

     Experience_Years Course_Level Scholarship Hostel Blood_Group
0                   2           UG          No     No          B+
1                   0           PG          No     No          A+
2                   2           PG         Yes    Yes          B-
3                   5           UG         Yes     No          O-
4                   7          PhD          No     No          O+
..                ...          ...         ...    ...         ...
995                 5           UG         Yes    Yes          A-
996                 3           UG         Yes     No          O+
997                 7           UG         Yes    Yes         AB+
998                 2           UG         Yes     No          B-
999                 8          PhD         Yes    Yes          O-

[1000 rows x 17 columns]

In [28]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

# Label Encoding
df["Course_Level"]=le.fit_transform(df["Course_Level"])
print(df)

     Student_ID    Age  Gender  Marks  Attendance_Percent Department  \
0             1  150.0    Male  -10.0                80.0       BCOM
1             2   21.0  Female   65.0                60.0        BBA
2             3   22.0    Male   65.0               100.0       BCOM
3             4  150.0    Male  -10.0                70.0       BCOM
4             5   20.0    Male  -10.0               100.0        BBA
..          ...    ...     ...    ...                 ...        ...
995         996   21.0  Female   75.0                80.0       BCOM
996         997   18.0    Male  -10.0                80.0        BCA
997         998  150.0    Male   75.0                70.0        BSc
998         999   21.0    Male   85.0               100.0        BCA
999        1000   21.0  Female  -10.0                90.0        BSc

          City            Email Fee_Paid Admission_Date  Income  Study_Hours  \
0       Mumbai          unknown       No     15-07-2023  136958          9.2
1    Bangalore          unknown      Yes     15-07-2023  146932          2.1
2      Chennai          unknown       No            NaN  118694          6.2
3       Mumbai          unknown       No     01-06-2023  134879          3.5
4      Chennai  valid@email.com       No     15-07-2023  125268          6.0
..         ...              ...      ...            ...     ...          ...
995     Mumbai  valid@email.com       No     15-07-2023   70961          6.0
996    Chennai          unknown       No            NaN  141678          6.4
997    Chennai          unknown       No            NaN   89532          7.1
998    Chennai          unknown       No     01-06-2023   96994          8.2
999      Delhi  valid@email.com       No     15-08-2023   71133          3.4

     Experience_Years  Course_Level Scholarship Hostel Blood_Group
0                   2             2          No     No          B+
1                   0             0          No     No          A+
2                   2             0         Yes    Yes          B-
3                   5             2         Yes     No          O-
4                   7             1          No     No          O+
..                ...           ...         ...    ...         ...
995                 5             2         Yes    Yes          A-
996                 3             2         Yes     No          O+
997                 7             2         Yes    Yes         AB+
998                 2             2         Yes     No          B-
999                 8             1         Yes    Yes          O-

[1000 rows x 17 columns]

In [29]:
# Binary encoding
df["Scholarship"]=df["Scholarship"].map({"Yes":1,"No":0})
df["Hostel"]=df["Hostel"].map({"Yes":1,"No":0})
df["Fee_Paid"]=df["Fee_Paid"].map({"Yes":1,"No":0})
print(df)

     Student_ID    Age  Gender  Marks  Attendance_Percent Department  \
0             1  150.0    Male  -10.0                80.0       BCOM
1             2   21.0  Female   65.0                60.0        BBA
2             3   22.0    Male   65.0               100.0       BCOM
3             4  150.0    Male  -10.0                70.0       BCOM
4             5   20.0    Male  -10.0               100.0        BBA
..          ...    ...     ...    ...                 ...        ...
995         996   21.0  Female   75.0                80.0       BCOM
996         997   18.0    Male  -10.0                80.0        BCA
997         998  150.0    Male   75.0                70.0        BSc
998         999   21.0    Male   85.0               100.0        BCA
999        1000   21.0  Female  -10.0                90.0        BSc

          City            Email  Fee_Paid Admission_Date  Income  Study_Hours  \
0       Mumbai          unknown         0     15-07-2023  136958          9.2
1    Bangalore          unknown         1     15-07-2023  146932          2.1
2      Chennai          unknown         0            NaN  118694          6.2
3       Mumbai          unknown         0     01-06-2023  134879          3.5
4      Chennai  valid@email.com         0     15-07-2023  125268          6.0
..         ...              ...       ...            ...     ...          ...
995     Mumbai  valid@email.com         0     15-07-2023   70961          6.0
996    Chennai          unknown         0            NaN  141678          6.4
997    Chennai          unknown         0            NaN   89532          7.1
998    Chennai          unknown         0     01-06-2023   96994          8.2
999      Delhi  valid@email.com         0     15-08-2023   71133          3.4

     Experience_Years  Course_Level  Scholarship  Hostel Blood_Group
0                   2             2            0       0          B+
1                   0             0            0       0          A+
2                   2             0            1       1          B-
3                   5             2            1       0          O-
4                   7             1            0       0          O+
..                ...           ...          ...     ...         ...
995                 5             2            1       1          A-
996                 3             2            1       0          O+
997                 7             2            1       1         AB+
998                 2             2            1       0          B-
999                 8             1            1       1          O-

[1000 rows x 17 columns]

In [30]:
# One-Hot encoding
df=pd.get_dummies(
    df,
    columns=["Blood_Group"],
    drop_first=True
)
print(df)

     Student_ID    Age  Gender  Marks  Attendance_Percent Department  \
0             1  150.0    Male  -10.0                80.0       BCOM
1             2   21.0  Female   65.0                60.0        BBA
2             3   22.0    Male   65.0               100.0       BCOM
3             4  150.0    Male  -10.0                70.0       BCOM
4             5   20.0    Male  -10.0               100.0        BBA
..          ...    ...     ...    ...                 ...        ...
995         996   21.0  Female   75.0                80.0       BCOM
996         997   18.0    Male  -10.0                80.0        BCA
997         998  150.0    Male   75.0                70.0        BSc
998         999   21.0    Male   85.0               100.0        BCA
999        1000   21.0  Female  -10.0                90.0        BSc

          City            Email  Fee_Paid Admission_Date  ...  \
0       Mumbai          unknown         0     15-07-2023  ...
1    Bangalore          unknown         1     15-07-2023  ...
2      Chennai          unknown         0            NaN  ...
3       Mumbai          unknown         0     01-06-2023  ...
4      Chennai  valid@email.com         0     15-07-2023  ...
..         ...              ...       ...            ...  ...
995     Mumbai  valid@email.com         0     15-07-2023  ...
996    Chennai          unknown         0            NaN  ...
997    Chennai          unknown         0            NaN  ...
998    Chennai          unknown         0     01-06-2023  ...
999      Delhi  valid@email.com         0     15-08-2023  ...

     Experience_Years  Course_Level  Scholarship  Hostel  Blood_Group_A-  \
0                   2             2            0       0           False
1                   0             0            0       0           False
2                   2             0            1       1           False
3                   5             2            1       0           False
4                   7             1            0       0           False
..                ...           ...          ...     ...             ...
995                 5             2            1       1            True
996                 3             2            1       0           False
997                 7             2            1       1           False
998                 2             2            1       0           False
999                 8             1            1       1           False

     Blood_Group_AB+  Blood_Group_B+  Blood_Group_B-  Blood_Group_O+  \
0              False            True           False           False
1              False           False           False           False
2              False           False            True           False
3              False           False           False           False
4              False           False           False            True
..               ...             ...             ...             ...
995            False           False           False           False
996            False           False           False            True
997             True           False           False           False
998            False           False            True           False
999            False           False           False           False

     Blood_Group_O-
0             False
1             False
2             False
3              True
4             False
..              ...
995           False
996           False
997           False
998           False
999            True

[1000 rows x 22 columns]

In [31]:
df.to_csv("cleaned_dateset.csv", index=False)
from google.colab import files
files.download("cleaned_dateset.csv")